title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
nav_external_links:
  - title: pccomponets
    url: https://www.pccomponentes.com/ofertas-especiales?s_kwcid=AL!14405!3!711122027019!b!!g!!pccomponentes&gad_source=1&gclid=EAIaIQobChMI3P6kq5qfiQMVCbKDBx3leBvzEAAYASAAEgKPVvD_BwE
    hide_icon: false
    opens_in_new_tab: true
